spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: after_route
          uri: lb://AMAZON-SERVICE-API
          predicates:
            - Path=/amazonConnect/**


server:
  port: 8092

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost




